### ISSUE TITLE
version 4.0 NameError: name 'no_temp' is not defined

### ISSUE THREAD

**Issue by yl315504** [cov-lineages/pangolin#419]
I have run pangolin for half a year. Each week I analyze Covid in DFW area. After Pangolin was updated this time, I got error complaining
"name 'no_temp' is not defined".

Below is the code I use. It was fine before Pangolin 4.0.

nohup pangolin --outdir /work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_30_COV119_11769_0/Project_JAS_2022_03_30_COV119_11769_0.trim.t0.5.ivar.fasta_pangolin_files \
--outfile Project_JAS_2022_03_30_COV119_11769_0.trim.t0.5.ivar.fasta.pangolin.txt \
--max-ambig 0.5 --no_temp \
--tempdir /work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_30_COV119_11769_0/Project_JAS_2022_03_30_COV119_11769_0.trim.t0.5.ivar.fasta_pangolin_files \
/work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_30_COV119_11769_0/Project_JAS_2022_03_30_COV119_11769_0.trim.t0.5.ivar.fasta &> output.txt &

**Comment by AngieHinrichs** [comment]
I have no idea why that would behave differently between pangolin v3 and v4, but the option should be `--no-temp` (with a dash) instead of `--no_temp` (with an underscore).

**Comment by yl315504** [comment]
It is a typo. I used "--no-temp".  Please see the code below. The code works for V3, but not V4.

nohup pangolin --outdir /work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_16_COV117_11718_0/S69_pangolin_files \
--outfile S69_pangolin.txt \
--max-ambig 0.5 --no-temp \
--tempdir /work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_16_COV117_11718_0/S69_pangolin_files \
/work/08270/yanliu74/ls6/UTSW_covid/Project_JAS_2022_03_16_COV117_11718_0/S69_22C_064M0132_20220125_144_C4.bwa.trim.t0.5.ivar.fa &> output.txt &

**Comment by yl315504** [comment]
I used "--no-temp", but the error massage shows "no_temp".
NameError: name 'no_temp' is not defined

**Comment by aineniamh** [comment]
Okay, it was a bug that only shows up if the pipeline fails for another reason. I've fixed that- but I suspect there might be something else that gets flagged with this update!

**Comment by aineniamh** [comment]
Fixed now in v4.0.4!

**Comment by yl315504** [comment]
As expected, we have a new error. NameError: name 'tempdir' is not defined.

I guess this new issue was caused by other issues. Is it possible to find the real issue?

**Comment by SamaZYX** [comment]
> As expected, we have a new error. NameError: name 'tempdir' is not defined.
> 
> I guess this new issue was caused by other issues. Is it possible to find the real issue?

I think it comes from a typo of variable tempdir in Line 248 and 250 in command.py . It should be args.tempdir or something like that.

And I still see the typo --no-tmp in line 56 in v4.0.4

**Comment by AngieHinrichs** [comment]
Thank you @SamaZYX for spotting those typos!  Lines 248 and 250 are executed only when there was an error in an earlier stage.

@yl315504 can you send the complete output of pangolin?  (You can attach the file `output.txt` from your command to this issue)

**Comment by yl315504** [comment]
@AngieHinrichs 

I attached the
[output.txt](https://github.com/cov-lineages/pangolin/files/8456136/output.txt)
![output_files](https://user-images.githubusercontent.com/25533752/162554291-f7f2c1f7-8094-4a81-b808-ab8d0e246805.PNG)
 output.txt and the files generated.

**Comment by yl315504** [comment]
I re-installed the environment. It works.

Thank you guys!

**Comment by aineniamh** [comment]
I've just fixed the typos flagged by @SamaZYX there- they only get called if something else fails within the pipeline, that's how they passed the tests, note to self: must add more tests. 

Sounds like the root issue was an install problem, glad it's sorted!
